name: CI/CD Pipeline for WebLogic Deployment

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to main branch

jobs:
  build:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build WAR file
        run: |
          mvn clean package -DskipTests

  sonar-analysis:
    runs-on:
      - self-hosted
      - linux
    needs: build
    steps:
      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://34.93.93.9:9000
          SONAR_TOKEN: sqa_05dff30184c6e2f5bf6d0bc2d56bfb30d9d9fe4e
        run: |
          source ~/.bashrc
          sonar-scanner -Dsonar.projectKey=oracledeployment -Dsonar.host.url=http://34.93.93.9:9000 -Dsonar.token=sqa_05dff30184c6e2f5bf6d0bc2d56bfb30d9d9fe4e -Dsonar.sources=. -Dsonar.java.binaries=target/classes
            
  deploy:
    runs-on:
      - self-hosted
      - linux
    needs: sonar-analysis 
    steps:
      - name: Deploy WAR file to WebLogic
        run: |
          chmod +x ./deploy_to_weblogic.sh
          ./deploy_to_weblogic.sh  # Run your deploy script
